project:
  type: website
  output-dir: _site

format:
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 18pt