project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "notebooks/Intro.ipynb"
    - "notebooks/Chapter_1.ipynb"
    - "notebooks/Chapter_2.ipynb"
    - "notebooks/Chapter_3.ipynb"
    - "notebooks/Chapter_4.ipynb"
    - "notebooks/Chapter_5.ipynb"
    - "notebooks/Chapter_6.ipynb"
    - "notebooks/Chapter_7.ipynb"
    - "notebooks/Chapter_8.ipynb"
    - "notebooks/Chapter_9.ipynb"
    - "notebooks/Chapter_10.ipynb"
    - "notebooks/Chapter_11.ipynb"

# Multi-format output configuration
format:
  # Website format (default)
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    code-fold: false
    code-tools: true
    highlight-style: github
    css: custom.css
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 13pt
  
  # RevealJS slides format
  revealjs:
    theme: [default, custom-reveal.scss]  # You can create a custom theme
    transition: slide
    background-transition: fade
    smaller: true
    scrollable: true
    incremental: false
    slide-number: true
    show-slide-number: all
    hash-type: number
    preview-links: auto
    chalkboard: true
    multiplex: false
    controls: true
    progress: true
    history: true
    center: true
    touch: true
    loop: false
    rtl: false
    shuffle: false
    fragments: true
    embedded: false
    help: true
    pause: true
    show-notes: false
    auto-slide: 0
    auto-slide-stoppable: true
    mouse-wheel: false
    hide-address-bar: true
    preload-iframes: false
    pdf-max-pages-per-slide: 1
    pdf-separate-fragments: true
    # Code highlighting for slides
    highlight-style: github
    code-line-numbers: false
    code-copy: false
    code-fold: false
    # Slide-specific styling
    fig-width: 8
    fig-height: 6
    fig-format: svg
    fig-dpi: 300
  
  # PDF format
  pdf:
    documentclass: book  # Changed from article for better chapter handling
    fontsize: 11pt
    mainfont: "DejaVu Sans"
    sansfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
    geometry:
      - top=25mm
      - bottom=25mm
      - left=20mm
      - right=20mm
    # PDF-specific settings
    highlight-style: github
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#e1e4e8"
    toc: true
    toc-depth: 3
    number-sections: true
    colorlinks: true
    lot: false  # List of tables
    lof: false  # List of figures
    # Page layout
    include-in-header: 
      - text: |
          \usepackage{fancyhdr}
          \pagestyle{fancy}
          \fancyhf{}
          \fancyhead[LE,RO]{\thepage}
          \fancyhead[LO,RE]{\leftmark}
    keep-tex: true  # Keep LaTeX source for debugging

filters:
  - quarto

# Language mappings for syntax highlighting
metadata:
  lang: en
  code-annotations: hover

website:
  title: "SystemVerilog Guide"
  description: "Comprehensive SystemVerilog Programming Guide"
  site-url: "https://ionutms.github.io/SystemVerilog_Learning"
  repo-url: "https://github.com/ionutms/SystemVerilog_Learning"
  site-path: "/SystemVerilog_Learning/"
  page-navigation: true
  
  navbar:
    title: "SystemVerilog Guide"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction" 
        href: notebooks/Intro.ipynb
    right:
      - icon: github
        href: https://github.com/ionutms/SystemVerilog_Learning
      - text: "PDF"
        href: "SystemVerilog-Guide.pdf"  # Link to generated PDF
      - text: "Slides"
        href: "slides/"  # Directory with slide presentations
  
  sidebar:
    style: "docked"
    search: true
    title: "Contents"
    contents:
      - index.qmd
      - notebooks/Intro.ipynb
      - text: "---"
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb