project:
  type: website
  output-dir: _site

format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - bottom=20mm
      - left=15mm
      - right=15mm
    # Enhanced PDF settings for better page control
    keep-tex: true
    code-line-numbers: true
    code-overflow: wrap
    fig-width: 7
    fig-height: 5
    fig-pos: 'H'
    
    # Add LaTeX packages for better page control (without titlesec conflicts)
    include-in-header:
      - text: |
          \usepackage{afterpage}
          \usepackage{float}
          \usepackage{fvextra}
          \usepackage{longtable}
          \usepackage{booktabs}
          \usepackage{needspace}
          
          % Prevent widows and orphans
          \widowpenalty=10000
          \clubpenalty=10000
          \raggedbottom
          
          % Add space before sections to prevent orphaned headers
          \makeatletter
          \renewcommand\section{%
            \needspace{4\baselineskip}%
            \@startsection{section}{1}{\z@}%
            {-3.5ex \@plus -1ex \@minus -.2ex}%
            {2.3ex \@plus.2ex}%
            {\normalfont\Large\bfseries}%
          }
          \renewcommand\subsection{%
            \needspace{3\baselineskip}%
            \@startsection{subsection}{2}{\z@}%
            {-3.25ex\@plus -1ex \@minus -.2ex}%
            {1.5ex \@plus .2ex}%
            {\normalfont\large\bfseries}%
          }
          \renewcommand\subsubsection{%
            \needspace{2\baselineskip}%
            \@startsection{subsubsection}{3}{\z@}%
            {-3.25ex\@plus -1ex \@minus -.2ex}%
            {1.5ex \@plus .2ex}%
            {\normalfont\normalsize\bfseries}%
          }
          \makeatother
          
          % Enhanced verbatim environment for code
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
            breaksymbolleft={}, 
            showspaces = false,
            showtabs = false,
            breaklines,
            commandchars=\\\{\}
          }
          
          % Better spacing around code blocks
          \BeforeBeginEnvironment{Highlighting}{\par\noindent\needspace{2\baselineskip}}
          \AfterEndEnvironment{Highlighting}{\par\addvspace{0.5\baselineskip}}
    
    # Control page breaks for different elements
    tbl-cap-location: top
    fig-cap-location: bottom
    
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 14pt

website:
  sidebar:
    contents:
      - notebooks/Intro.ipynb
      - text: "---"
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb
      - notebooks/Chapter_12.ipynb
      - notebooks/Chapter_13.ipynb
      - notebooks/Chapter_14.ipynb
      - text: "---"
      - text: "Part IV: Verification Features"
      - text: "---"
      - notebooks/systemverilog_learning_resources.ipynb