project:
  type: website

website:
  title: "SystemVerilog Learning Resources"
  navbar:
    left:
      - href: systemverilog_learning_resources.ipynb
        text: "Learning Guide"
    right:
      - icon: github
        href: https://github.com/ionutms/SystemVerilog_Learning

format:
  html:
    theme: cosmo
    code-copy: true
    code-line-numbers: true
    toc: true
    search: true