project:
  type: website

website:
  title: "SystemVerilog Learning Resources"
  navbar:
    left:
      - href: systemverilog_learning_resources.ipynb
        text: "Learning Guide"
    right:
      - icon: github
        href: https://github.com/ionutms/SystemVerilog_Learning

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    code-copy: true
    code-line-numbers: true
    toc: true
    toc-depth: 4        # Increased to capture more heading levels
    toc-location: left
    toc-title: "Contents"
    toc-expand: 2       # Auto-expand first 2 levels
    search: true
    smooth-scroll: true
    css: 
      - styles.css      # Custom CSS for better TOC styling
    grid:
      sidebar-width: 300px  # Wider sidebar for better TOC readability
      body-width: 900px
      margin-width: 200px