# === QUARTO PROJECT CONFIGURATION ===
project:
  type: website              # Project type: website, book, or manuscript
  output-dir: _site         # Directory where rendered files will be placed
  
  # === RENDER CONFIGURATION ===
  # List of files to render (in order)
  # Currently rendering chapters 1-11, with 12+ commented out for development
  render:
    - "index.qmd"                    # Homepage
    - "notebooks/Intro.ipynb"        # Introduction notebook
    - "notebooks/Chapter_1.ipynb"    # Active chapters
    - "notebooks/Chapter_2.ipynb"
    - "notebooks/Chapter_3.ipynb"
    - "notebooks/Chapter__4_0.ipynb"
    - "notebooks/Chapter__4_1.ipynb"
    - "notebooks/Chapter__4_2.ipynb"
    - "notebooks/Chapter__4_3.ipynb"
    - "notebooks/Chapter__4_4.ipynb"
    - "notebooks/Chapter__4_5.ipynb"
    - "notebooks/Chapter_5.ipynb"
    - "notebooks/Chapter_6.ipynb"
    - "notebooks/Chapter_7.ipynb"
    - "notebooks/Chapter_8.ipynb"
    - "notebooks/Chapter_9.ipynb"
    - "notebooks/Chapter_10.ipynb"
    - "notebooks/Chapter_11.ipynb"
    # Commented out chapters (uncomment when ready to include)
    # - "notebooks/Chapter_12.ipynb"
    # - "notebooks/Chapter_13.ipynb"
    # - "notebooks/Chapter_14.ipynb"
    # - "notebooks/Chapter_15.ipynb"
    # - "notebooks/Chapter_16.ipynb"
    # - "notebooks/Chapter_17.ipynb"
    # - "notebooks/Chapter_18.ipynb"
    # - "notebooks/Chapter_19.ipynb"
    # - "notebooks/Chapter_20.ipynb"
    # - "notebooks/Chapter_21.ipynb"
    # - "notebooks/Chapter_22.ipynb"
    # - "notebooks/Chapter_23.ipynb"
    # - "notebooks/Chapter_24.ipynb"
    # - "notebooks/Chapter_25.ipynb"
    # - "notebooks/Chapter_26.ipynb"
    # - "notebooks/Appendix_A.ipynb"
    # - "notebooks/Appendix_B.ipynb"
    # - "notebooks/Appendix_C.ipynb"
    # - "notebooks/Appendix_D.ipynb"
    # - "notebooks/Appendix_E.ipynb"
    # - "notebooks/Appendix_F.ipynb"
    # - "notebooks/Appendix_G.ipynb"

format:
  pdf:
    # LaTeX document class - 'article' is good for academic/technical documents
    documentclass: article
    
    # Font size for the entire document (8pt, 9pt, 10pt, 11pt, 12pt)
    fontsize: 10pt
    
    # Font families for different text types
    mainfont: "DejaVu Sans"      # Main body text font
    sansfont: "DejaVu Sans"      # Sans-serif font (used for headings by default)
    monofont: "DejaVu Sans Mono" # Monospace font (used for code blocks)
    
    # Page margins configuration
    geometry:
      - top=20mm     # Top margin
      - bottom=20mm  # Bottom margin
      - left=15mm    # Left margin
      - right=15mm   # Right margin
    
    # Syntax highlighting and code block styling for PDF
    highlight-style: github                    # Code syntax highlighting theme
    code-block-bg: "#f8f8f8"                 # Background color for code blocks
    code-block-border-left: "#e1e4e8"        # Left border color for code blocks
    
    # ===== PAGE BREAK CONTROLS FOR HEADERS =====
    # This section adds LaTeX commands to control how headers behave near page breaks
    include-in-header:
      - text: |
          % Import titlesec package for advanced header formatting
          \usepackage{titlesec}
          
          % Format all header levels consistently
          % Level 1: section (# in Markdown)
          \titleformat{\section}
            {\normalfont\Large\bfseries}      % Font: normal, Large, bold
            {\thesection}                     % Section number
            {1em}                             % Space between number and title
            {}                                % Before-code (empty)
          
          % Level 2: subsection (## in Markdown)
          \titleformat{\subsection}
            {\normalfont\large\bfseries}      % Font: normal, large, bold
            {\thesubsection}                  % Section number format
            {1em}                             % Space between number and title
            {}                                % Before-code (empty)
          
          % Level 3: subsubsection (### in Markdown)
          \titleformat{\subsubsection}
            {\normalfont\normalsize\bfseries} % Font: normal, normal size, bold
            {\thesubsubsection}               % Section number format
            {1em}                             % Space between number and title
            {}                                % Before-code (empty)
          
          % Level 4: paragraph (#### in Markdown)
          \titleformat{\paragraph}
            {\normalfont\normalsize\bfseries} % Font: normal, normal size, bold
            {\theparagraph}                   % Section number format
            {1em}                             % Space between number and title
            {}                                % Before-code (empty)
          
          % Level 5: subparagraph (##### in Markdown)
          \titleformat{\subparagraph}
            {\normalfont\small\bfseries}      % Font: normal, small, bold
            {\thesubparagraph}                % Section number format
            {1em}                             % Space between number and title
            {}                                % Before-code (empty)
          
          % Control spacing around all header levels
          % Syntax: \titlespacing*{command}{left}{before-sep}{after-sep}[right-sep]
          
          % Level 1: section spacing
          \titlespacing*{\section}
            {0pt}                         % Left indent
            {3.5ex plus 1ex minus .2ex}   % Space before header (more than subsection)
            {2.3ex plus .2ex}             % Space after header
          
          % Level 2: subsection spacing
          \titlespacing*{\subsection}
            {0pt}                         % Left indent
            {3.25ex plus 1ex minus .2ex}  % Space before header
            {1.5ex plus .2ex}             % Space after header
          
          % Level 3: subsubsection spacing
          \titlespacing*{\subsubsection}
            {0pt}                         % Left indent
            {3.25ex plus 1ex minus .2ex}  % Space before header
            {1.5ex plus .2ex}             % Space after header
          
          % Level 4: paragraph spacing
          \titlespacing*{\paragraph}
            {0pt}                         % Left indent
            {3.25ex plus 1ex minus .2ex}  % Space before header
            {1em}                         % Space after header (smaller)
          
          % Level 5: subparagraph spacing
          \titlespacing*{\subparagraph}
            {0pt}                         % Left indent
            {3.25ex plus 1ex minus .2ex}  % Space before header
            {1em}                         % Space after header (smaller)
          
          % === MAIN SOLUTION: Prevent orphaned headers ===
          % Import needspace package - ensures minimum space before placing content
          \usepackage{needspace}
          
          % === APPLY PAGE BREAK CONTROL TO ALL HEADER LEVELS ===
          
          % Level 1 Headers: # in Markdown (section in LaTeX)
          % Save original section command and redefine with needspace
          \let\oldsection\section
          \renewcommand{\section}[1]{\needspace{5\baselineskip}\oldsection{#1}}
          
          % Level 2 Headers: ## in Markdown (subsection in LaTeX)
          % Save original subsection command and redefine with needspace
          \let\oldsubsection\subsection
          \renewcommand{\subsection}[1]{\needspace{4\baselineskip}\oldsubsection{#1}}
          
          % Level 3 Headers: ### in Markdown (subsubsection in LaTeX)
          % Save original subsubsection command and redefine with needspace
          \let\oldsubsubsection\subsubsection
          \renewcommand{\subsubsection}[1]{\needspace{3\baselineskip}\oldsubsubsection{#1}}
          
          % Level 4 Headers: #### in Markdown (paragraph in LaTeX)
          % Save original paragraph command and redefine with needspace
          \let\oldparagraph\paragraph
          \renewcommand{\paragraph}[1]{\needspace{3\baselineskip}\oldparagraph{#1}}
          
          % Level 5 Headers: ##### in Markdown (subparagraph in LaTeX)
          % Save original subparagraph command and redefine with needspace
          \let\oldsubparagraph\subparagraph
          \renewcommand{\subparagraph}[1]{\needspace{2\baselineskip}\oldsubparagraph{#1}}
          
          % EXPLANATION OF NEEDSPACE VALUES:
          % - Level 1 (5 lines): Most important, needs most space
          % - Level 2 (4 lines): Important section headers
          % - Level 3 (3 lines): Subsection headers
          % - Level 4 (3 lines): Smaller headers but still need space
          % - Level 5 (2 lines): Minimal space requirement
          % 
          % You can adjust these values based on your preferences:
          % - Increase for more aggressive page breaking
          % - Decrease for more compact layout
          
          % === ALTERNATIVE APPROACH (commented out) ===
          % Different method using titlesec's built-in page break controls
          % \titleformat{\subsection}[hang]
          %   {\normalfont\large\bfseries}{\thesubsection}{1em}{}
          %   [\titlerule]  % Adds horizontal rule after header
          % \titlespacing*{\subsection}{0pt}{3.25ex plus 1ex minus .2ex}{1.5ex plus .2ex}
          
          % === PREVENT WIDOWS AND ORPHANS ===
          % Widow = single line at top of page from previous paragraph
          % Orphan = single line at bottom of page from next paragraph
          % 10000 = very high penalty (almost never allow)
          \widowpenalty=10000   % Prevent widows
          \clubpenalty=10000    % Prevent orphans
          
          % === ADDITIONAL PAGE BREAK CONTROLS ===
          % Import sectsty package for section styling
          \usepackage{sectsty}
          
          % \pagebreak[n] where n = 0-4 (0=no preference, 4=strong preference)
          % [3] = encourage page break before section if needed
          % Apply to all header levels for consistent behavior
          \sectionfont{\pagebreak[3]}         % For level 1 headers (# in Markdown)
          \subsectionfont{\pagebreak[3]}      % For level 2 headers (## in Markdown)
          \subsubsectionfont{\pagebreak[2]}   % For level 3 headers (### in Markdown)
          \paragraphfont{\pagebreak[2]}       % For level 4 headers (#### in Markdown)
          \subparagraphfont{\pagebreak[1]}    % For level 5 headers (##### in Markdown)
          
          % EXPLANATION OF PAGEBREAK VALUES:
          % [3] = Strong preference for page break (levels 1-2)
          % [2] = Moderate preference for page break (levels 3-4)
          % [1] = Weak preference for page break (level 5)
          % This creates a hierarchy where more important headers
          % are more likely to start on a new page
          
          % === EXPLANATION OF UNITS ===
          % \baselineskip = height of one line of text
          % ex = height of letter 'x' in current font
          % em = width of letter 'M' in current font
          % pt = point (1/72 inch)
          % mm = millimeter
  
  html:
    # === HTML OUTPUT CONFIGURATION ===
    # Full page layout without sidebar constraints
    page-layout: full
    
    # Grid system configuration
    grid: 
      body-width: 1200px  # Maximum width for content area
    
    # Theme configuration for light/dark mode
    theme:
      dark: darkly   # Dark theme name (Bootstrap-based)
      light: cosmo   # Light theme name (Bootstrap-based)
    
    # === CODE BLOCK FEATURES ===
    code-copy: true           # Add copy button to code blocks
    code-line-numbers: true   # Show line numbers in code blocks
    code-overflow: wrap       # Wrap long lines instead of horizontal scroll
    code-fold: false          # Don't collapse code blocks by default
    code-tools: true          # Show code tools (view source, etc.)
    
    # Syntax highlighting theme (same as PDF for consistency)
    highlight-style: github
    
    # Custom CSS file for additional styling
    css: custom.css
    
    # === TABLE OF CONTENTS (TOC) CONFIGURATION ===
    toc: true                 # Enable table of contents
    toc-depth: 6             # Include headings up to level 6 (######)
    toc-location: right      # Position TOC on right side
    toc-title: "Contents"    # Title for TOC section
    
    # === ADDITIONAL HTML FEATURES ===
    search: true             # Enable search functionality
    fontsize: 13pt          # Base font size for HTML output

# === QUARTO FILTERS AND PROCESSING ===
filters:
  - quarto  # Default Quarto filter for processing

# === DOCUMENT METADATA ===
# Global metadata applied to all documents
metadata:
  lang: en                    # Document language (affects hyphenation, etc.)
  code-annotations: hover     # How code annotations are displayed

# === WEBSITE CONFIGURATION ===
website:
  # === SITE IDENTITY ===
  title: "SystemVerilog Guide"
  description: "Comprehensive SystemVerilog Programming Guide"
  
  # === DEPLOYMENT CONFIGURATION ===
  # URLs for the live site and source repository
  site-url: "https://ionutms.github.io/SystemVerilog_Learning"
  repo-url: "https://github.com/ionutms/SystemVerilog_Learning"
  
  # GitHub Pages project sites need a base path (not root domain)
  # This ensures all links work correctly when deployed
  site-path: "/SystemVerilog_Learning/"
  
  # === NAVIGATION FEATURES ===
  page-navigation: true  # Enable prev/next page navigation
  
  # === TOP NAVIGATION BAR ===
  navbar:
    title: "SystemVerilog Guide"  # Brand name in navbar
    left:  # Left-aligned navigation items
      - text: "Home"
        href: index.qmd
      - text: "Introduction" 
        href: notebooks/Intro.ipynb
  
  # === SIDEBAR CONFIGURATION ===
  sidebar:
    style: "docked"      # Sidebar style: docked, floating, or push
    search: true         # Enable search within sidebar
    title: "Contents"    # Sidebar title
    
    # === SIDEBAR CONTENT STRUCTURE ===
    # Defines the hierarchical structure of the site
    contents:
      - index.qmd                    # Homepage
      - notebooks/Intro.ipynb        # Introduction
      - text: "---"                  # Horizontal separator
      
      # === PART I: FUNDAMENTALS ===
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      
      # === PART II: DESIGN CONSTRUCTS ===
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      
      # === PART III: OBJECT-ORIENTED PROGRAMMING ===
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb
      - text: "---"
      
      # === FUTURE PARTS (currently commented out in render) ===
      # These will be activated when corresponding chapters are uncommented
      - text: "Part IV: Verification Features"
      - notebooks/Chapter_12.ipynb
      - notebooks/Chapter_13.ipynb
      - notebooks/Chapter_14.ipynb
      - notebooks/Chapter_15.ipynb
      - text: "---"
      
      - text: "Part V: Advanced Verification"
      - notebooks/Chapter_16.ipynb
      - notebooks/Chapter_17.ipynb
      - notebooks/Chapter_18.ipynb
      - notebooks/Chapter_19.ipynb
      - text: "---"
      
      - text: "Part VI: Practical Applications"
      - notebooks/Chapter_20.ipynb
      - notebooks/Chapter_21.ipynb
      - notebooks/Chapter_22.ipynb
      - notebooks/Chapter_23.ipynb
      - text: "---"
      
      - text: "Part VII: Advanced Topics"
      - notebooks/Chapter_24.ipynb
      - notebooks/Chapter_25.ipynb
      - notebooks/Chapter_26.ipynb
      - text: "---"
      
      # === APPENDICES ===
      - text: "Appendices"
      - notebooks/Appendix_A.ipynb
      - notebooks/Appendix_B.ipynb
      - notebooks/Appendix_C.ipynb
      - notebooks/Appendix_D.ipynb
      - notebooks/Appendix_E.ipynb
      - notebooks/Appendix_F.ipynb
      - notebooks/Appendix_G.ipynb
      - text: "---"