project:
  type: website
  output-dir: _site

format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - bottom=20mm
      - left=15mm
      - right=15mm
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 14pt

website:
  sidebar:
    contents:
      - notebooks/Intro.ipynb
      - text: "---"
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb
      - text: "---"
      - text: "Part IV: Verification Features"
      - notebooks/Chapter_12.ipynb
      - notebooks/Chapter_13.ipynb
      - notebooks/Chapter_14.ipynb
      - notebooks/Chapter_15.ipynb
      - text: "---"
      - text: "Part V: Advanced Verification"
      - notebooks/Chapter_16.ipynb
      - notebooks/Chapter_17.ipynb
      - notebooks/Chapter_18.ipynb
      - notebooks/Chapter_19.ipynb
      - text: "---"
      - text: "Part VI: Practical Applications"
      - notebooks/Chapter_20.ipynb
      - notebooks/Chapter_21.ipynb
      - notebooks/Chapter_22.ipynb
      - notebooks/Chapter_23.ipynb
      - text: "---"
      - text: "Part VII: Advanced Topics"
      - notebooks/Chapter_24.ipynb
      - notebooks/Chapter_25.ipynb
      - notebooks/Chapter_26.ipynb
      - text: "---"
      - text: "Appendices"
      - text: "---"
      - notebooks/systemverilog_learning_resources.ipynb