project:
  type: website

website:
  title: "SystemVerilog Learning Resources"
  navbar:
    left:
      - href: systemverilog_learning_resources.ipynb
        text: "Learning Guide"
    right:
      - icon: github
        href: https://github.com/ionutms/SystemVerilog_Learning

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    code-copy: true
    code-line-numbers: true
    toc: true
    toc-depth: 3        # How many heading levels to include
    toc-location: left  # left, right, body
    toc-title: "Contents"
    search: true