project:
  type: website
  output-dir: _site

format:
  pdf:
    documentclass: article
    geometry:
      - top=20mm
      - bottom=20mm
      - left=15mm
      - right=15mm
    # Enhanced PDF settings for better page control
    keep-tex: true
    code-line-numbers: true
    code-overflow: wrap
    fig-width: 7
    fig-height: 5
    fig-pos: 'H'
    # Add LaTeX packages for better page control
    include-in-header:
      - text: |
          \usepackage{afterpage}
          \usepackage{float}
          \usepackage{fvextra}
          \usepackage{longtable}
          \usepackage{booktabs}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{
            breaksymbolleft={}, 
            showspaces = false,
            showtabs = false,
            breaklines,
            commandchars=\\\{\}
          }
    # Control page breaks for different elements
    tbl-cap-location: top
    fig-cap-location: bottom
    
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 14pt

website:
  sidebar:
    contents:
      - notebooks/Intro.ipynb
      - text: "---"
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb
      - notebooks/Chapter_12.ipynb
      - notebooks/Chapter_13.ipynb
      - notebooks/Chapter_14.ipynb
      - text: "---"
      - text: "Part IV: Verification Features"
      - text: "---"
      - notebooks/systemverilog_learning_resources.ipynb