project:
  type: website
  output-dir: _site
  render:
    - "index.qmd"
    - "notebooks/Intro.ipynb"
    - "notebooks/Chapter_1.ipynb"
    - "notebooks/Chapter_2.ipynb"
    - "notebooks/Chapter_3.ipynb"
    - "notebooks/Chapter_4.ipynb"
    - "notebooks/Chapter_5.ipynb"
    - "notebooks/Chapter_6.ipynb"
    - "notebooks/Chapter_7.ipynb"
    - "notebooks/Chapter_8.ipynb"
    - "notebooks/Chapter_9.ipynb"
    - "notebooks/Chapter_10.ipynb"
    - "notebooks/Chapter_11.ipynb"
    # - "notebooks/Chapter_12.ipynb"
    # - "notebooks/Chapter_13.ipynb"
    # - "notebooks/Chapter_14.ipynb"
    # - "notebooks/Chapter_15.ipynb"
    # - "notebooks/Chapter_16.ipynb"
    # - "notebooks/Chapter_17.ipynb"
    # - "notebooks/Chapter_18.ipynb"
    # - "notebooks/Chapter_19.ipynb"
    # - "notebooks/Chapter_20.ipynb"
    # - "notebooks/Chapter_21.ipynb"
    # - "notebooks/Chapter_22.ipynb"
    # - "notebooks/Chapter_23.ipynb"
    # - "notebooks/Chapter_24.ipynb"
    # - "notebooks/Chapter_25.ipynb"
    # - "notebooks/Chapter_26.ipynb"
    # - "notebooks/Appendix_A.ipynb"
    # - "notebooks/Appendix_B.ipynb"
    # - "notebooks/Appendix_C.ipynb"
    # - "notebooks/Appendix_D.ipynb"
    # - "notebooks/Appendix_E.ipynb"
    # - "notebooks/Appendix_F.ipynb"
    # - "notebooks/Appendix_G.ipynb"

format:
  pdf:
    documentclass: article
    fontsize: 10pt
    mainfont: "DejaVu Sans"
    sansfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
    geometry:
      - top=20mm
      - bottom=20mm
      - left=15mm
      - right=15mm
    # PDF-specific code formatting
    highlight-style: github
    code-block-bg: "#f8f8f8"
    code-block-border-left: "#e1e4e8"
  html:
    page-layout: full
    grid: 
      body-width: 1200px
    theme:
      dark: darkly
      light: cosmo
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    code-fold: false
    code-tools: true
    # Syntax highlighting
    highlight-style: github
    # Code block styling
    css: custom.css
    toc: true
    toc-depth: 6
    toc-location: right
    toc-title: "Contents"
    search: true
    fontsize: 13pt
  revealjs:
    theme: [default, custom.css]
    transition: slide
    slide-number: true
    scrollable: true
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    highlight-style: github
    incremental: false
    controls: true
    progress: true
    history: true
    center: true
    toc: true
    toc-depth: 6
    fontsize: 13pt

filters:
  - quarto

# Language mappings for syntax highlighting
metadata:
  lang: en
  code-annotations: hover

website:
  title: "SystemVerilog Guide"
  description: "Comprehensive SystemVerilog Programming Guide"
  site-url: "https://ionutms.github.io/SystemVerilog_Learning"
  repo-url: "https://github.com/ionutms/SystemVerilog_Learning"
  
  # Fixed: Add proper base path for GitHub Pages project site
  site-path: "/SystemVerilog_Learning/"
  
  # Fixed: Add page navigation and homepage settings
  page-navigation: true
  
  # Add navbar
  navbar:
    title: "SystemVerilog Guide"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction" 
        href: notebooks/Intro.ipynb
    right:
      - icon: github
        href: "https://github.com/ionutms/SystemVerilog_Learning"
  
  sidebar:
    style: "docked"
    search: true

    title: "Contents"
    contents:
      - index.qmd
      - notebooks/Intro.ipynb
      - text: "---"
      - text: "Part I: Fundamentals"
      - notebooks/Chapter_1.ipynb
      - notebooks/Chapter_2.ipynb
      - notebooks/Chapter_3.ipynb
      - notebooks/Chapter_4.ipynb
      - text: "---"
      - text: "Part II: Design Constructs"
      - notebooks/Chapter_5.ipynb
      - notebooks/Chapter_6.ipynb
      - notebooks/Chapter_7.ipynb
      - notebooks/Chapter_8.ipynb
      - text: "---"
      - text: "Part III: Object-Oriented Programming"
      - notebooks/Chapter_9.ipynb
      - notebooks/Chapter_10.ipynb
      - notebooks/Chapter_11.ipynb
      - text: "---"
      - text: "Part IV: Verification Features"
      - notebooks/Chapter_12.ipynb
      - notebooks/Chapter_13.ipynb
      - notebooks/Chapter_14.ipynb
      - notebooks/Chapter_15.ipynb
      - text: "---"
      - text: "Part V: Advanced Verification"
      - notebooks/Chapter_16.ipynb
      - notebooks/Chapter_17.ipynb
      - notebooks/Chapter_18.ipynb
      - notebooks/Chapter_19.ipynb
      - text: "---"
      - text: "Part VI: Practical Applications"
      - notebooks/Chapter_20.ipynb
      - notebooks/Chapter_21.ipynb
      - notebooks/Chapter_22.ipynb
      - notebooks/Chapter_23.ipynb
      - text: "---"
      - text: "Part VII: Advanced Topics"
      - notebooks/Chapter_24.ipynb
      - notebooks/Chapter_25.ipynb
      - notebooks/Chapter_26.ipynb
      - text: "---"
      - text: "Appendices"
      - notebooks/Appendix_A.ipynb
      - notebooks/Appendix_B.ipynb
      - notebooks/Appendix_C.ipynb
      - notebooks/Appendix_D.ipynb
      - notebooks/Appendix_E.ipynb
      - notebooks/Appendix_F.ipynb
      - notebooks/Appendix_G.ipynb
      - text: "---"