project:
  type: website

website:
  title: "Your Website Title"
  
  # Mobile-friendly navigation
  navbar:
    background: primary
    search: true
    collapse-below: lg  # Collapse navigation on smaller screens
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/yourusername/yourrepo
        aria-label: "GitHub"
  
  # Responsive sidebar
  sidebar:
    collapse-level: 2
    contents: auto
    # Custom mobile behavior
    tools:
      - icon: github
        href: https://github.com/yourusername/yourrepo

format:
  html:
    # Mobile-optimized settings
    theme: cosmo
    
    # Responsive TOC
    toc: true
    toc-location: left
    toc-expand: 1
    toc-depth: 3
    
    # Mobile-friendly layout
    page-layout: article
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
    
    # Better mobile typography
    fontsize: 1.1em
    linestretch: 1.7
    
    # Mobile navigation
    anchor-sections: true
    smooth-scroll: true
    
    # Responsive images and tables
    fig-responsive: true
    tbl-responsive: true
    
    # Mobile-optimized code blocks
    code-fold: true
    code-summary: "Show code"
    code-overflow: wrap
    
    # Custom CSS for mobile responsiveness
    css: |
      /* Mobile-first responsive design */
      html {
        font-size: 16px;
      }
      
      body {
        line-height: 1.6;
      }
      
      /* Mobile Navigation */
      @media (max-width: 768px) {
        .navbar-collapse {
          text-align: center;
        }
        
        .navbar-nav .nav-link {
          padding: 0.75rem 1rem;
          display: block;
        }
        
        /* Mobile Sidebar/TOC */
        .sidebar-navigation {
          position: relative !important;
          width: 100% !important;
          margin-bottom: 1.5rem;
          max-height: 250px;
          overflow-y: auto;
          border: 1px solid #dee2e6;
          border-radius: 8px;
          background: #f8f9fa;
          padding: 1rem;
        }
        
        /* Compact TOC */
        .toc-actions {
          font-size: 0.9em;
        }
        
        .toc-actions a {
          padding: 8px 12px;
          display: block;
          border-radius: 4px;
          margin: 2px 0;
          text-decoration: none;
          color: #333;
        }
        
        .toc-actions a:hover {
          background-color: #e9ecef;
        }
        
        .toc-actions .active > a {
          background-color: #007bff;
          color: white;
        }
        
        /* Content adjustments */
        .quarto-container {
          padding: 1rem;
          max-width: 100%;
        }
        
        /* Responsive text */
        h1 { font-size: 1.8rem; }
        h2 { font-size: 1.5rem; }
        h3 { font-size: 1.3rem; }
        h4 { font-size: 1.1rem; }
        
        /* Code blocks */
        pre {
          font-size: 0.8rem;
          overflow-x: auto;
          white-space: pre-wrap;
          word-wrap: break-word;
          padding: 1rem;
        }
        
        /* Tables */
        .table-responsive {
          font-size: 0.85rem;
        }
        
        .table th, .table td {
          padding: 0.5rem 0.25rem;
          white-space: nowrap;
        }
        
        /* Images */
        img {
          max-width: 100%;
          height: auto;
        }
        
        /* Figures */
        .figure {
          margin: 1rem 0;
        }
        
        .figure-caption {
          font-size: 0.9rem;
          margin-top: 0.5rem;
        }
        
        /* Better spacing for lists */
        ul, ol {
          padding-left: 1.5rem;
        }
        
        /* Code folding button */
        .code-fold .btn {
          font-size: 0.8rem;
          padding: 0.25rem 0.5rem;
        }
      }
      
      /* Tablet styles */
      @media (min-width: 769px) and (max-width: 1024px) {
        .sidebar-navigation {
          width: 250px !important;
        }
        
        .quarto-container {
          max-width: 95%;
        }
      }
      
      /* Touch-friendly elements */
      @media (hover: none) and (pointer: coarse) {
        button, .btn {
          min-height: 44px;
          min-width: 44px;
          padding: 0.75rem 1rem;
        }
        
        .toc-actions a {
          min-height: 44px;
          display: flex;
          align-items: center;
        }
        
        .nav-link {
          min-height: 44px;
          display: flex;
          align-items: center;
        }
      }
      
      /* Small mobile devices */
      @media (max-width: 480px) {
        .quarto-container {
          padding: 0.5rem;
        }
        
        h1 { font-size: 1.6rem; }
        h2 { font-size: 1.4rem; }
        h3 { font-size: 1.2rem; }
        
        .sidebar-navigation {
          max-height: 180px;
          padding: 0.75rem;
        }
        
        .toc-actions {
          font-size: 0.85em;
        }
        
        pre {
          font-size: 0.75rem;
          padding: 0.75rem;
        }
      }
      
      /* Print styles */
      @media print {
        .sidebar-navigation,
        .navbar,
        .quarto-search,
        .code-fold {
          display: none !important;
        }
        
        .quarto-container {
          max-width: none !important;
          padding: 0 !important;
        }
        
        body {
          font-size: 12pt;
          line-height: 1.4;
        }
      }

# Additional mobile optimizations
execute:
  freeze: auto  # Faster builds

# SEO and mobile metadata
website:
  open-graph: true
  twitter-card: true
  google-analytics: "G-XXXXXXXXXX"  # Optional: Add your GA ID
  
  # PWA-like features (optional)
  favicon: favicon.ico
  
  # Mobile-specific meta tags
  page-footer: |
    <div class="nav-footer-center">
      <div class="toc-actions d-sm-none">
        <a href="#top">Back to top</a>
      </div>
    </div>